language: java
jdk:
  - java-11-openjdk-devel

addons:
  apt:
    packages:
      - python3-lxml

deploy:
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh master
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: automation/deploy-on-gh-pages.sh tagged
    on:
      tags: true
